## Use qemu-img to convert to the available formats
## raw, qcow2, vmdk, vdi, vhd, vhdx, qcow1, and more
## use qemu-img --help to find all supported formats
#CONVERT=none

## You can select a device to install to rather than
## creating an image. THIS WILL DESTROY ***ALL***
## DATA ON THE SELECTED DEVICE
#DEVICE=/dev/sda

## Configure the size of the EFI partition. Note that
## the system is configured to use Unified Kernel
## Images
#EFI_SIZE=512M

## If installing to a device, do not prompt for
## confirmation
SKIP_DESTRUCTION_WARNING=true

## Set locale in locale.gen
#LOCALE=en_US.UTF-8 UTF-8

## Set lang in locale.conf
#LANG=en_US.UTF-8

## Set hostname
#HOSTNAME=mediabox

## Save the image as
#OUTPUT_NAME=plasmabigscreen.img

## Set the password for root and the new user
#PASSWORD=plasma

## Set the size of the image, it must be large enough for the
## install to complete
#IMAGE_SIZE=10G

## Set the username for the default user
#USER=boxuser

## Expand the image after creation
#EXPAND_IMAGE=no

## Where to find the 'mediabox' directory (no trailing slash)
## For the docker install this should be "/opt/bigscreen-quickdeploy"
SOURCE=/opt/bigscreen-quickdeploy

## UNIX sockets have a limit of 108 characters which can be an issue in this case.
## If you run into errors with pacman try enabling this option and or moving
## this repo to a shorter path like /root rather than /home/user/Downloads
#STUPID_UNIX=false